### ISSUE TITLE
ModelObjectWrapped code

### ISSUE THREAD

**Issue by mikeedi** [perwin/pyimfit#1]
Where I can find source code of ModelObjectWrapped class?
How CreateModelIMage works?

**Comment by perwin** [comment]
The ModelObjectWrapper class is defined in the Cython file pyimfit_lib.pyx
https://github.com/perwin/pyimfit/blob/master/pyimfit/pyimfit_lib.pyx

**Comment by perwin** [comment]
(I'm a little confused about your question, since the second part suggests you already know about pyimfit_lib.pyx...)

**Comment by perwin** [comment]
I'm going to close this, since I haven't heard back from you (but feel free to re-open this if you still have questions!).
