### ISSUE TITLE
offset in aperture fluxes?

### ISSUE THREAD

**Issue by JohannesBuchner** [perwin/pyimfit#10]
Dear Peter,

I am working with a catalog listing aperture fluxes from catalogs extracted with several radii, in addition to b/a. I was wondering whether I can use imfit to generate galaxies with a central point source and predict aperture fluxes for comparison.

My test code is below. I am using photutils to compute aperture fluxes. 

But it seems that there is a 2-pixel offset between the center of the generated source and the aperture position.

Here are the aperture fluxes as a function of radius. Only the one offset by 2 pixels peaks at the center:
![apflux](https://github.com/user-attachments/assets/dcafb6ef-7d3e-47ba-8437-3f258783733d)
Here is the generated image:
![GAL](https://github.com/user-attachments/assets/b1098793-f8aa-44c1-affd-6b0d720fc046)

```
import matplotlib.pyplot as plt
from astropy.io import fits
import pyimfit

def PSF_model(sigma, x0=10, y0=10):
    model = pyimfit.SimpleModelDescription()
    # define the limits on X0 and Y0 as +/-10 pixels relative to initial values
    model.x0.setValue(x0, [x0 - 10, x0 + 10])
    model.y0.setValue(y0, [y0 - 10, y0 + 10])

    psf = pyimfit.make_imfit_function('Gaussian', label='PSF')
    psf.I_0.setValue(1, [0, 10])
    psf.sigma.setValue(sigma, [0, 10])
    
    model.addFunction(psf)
    return model


psf_imgfitter = pyimfit.Imfit(PSF_model(sigma=0.5, x0=20, y0=20))

psf_model_img = psf_imgfitter.getModelImage(shape=(40, 40))

#print(psf_model_img)
plt.imshow(psf_model_img)
plt.savefig('PSF.pdf')
plt.close()

# define a function for making a simple bulge+disk model, where both components
# share the same central coordinate (SimpleModelDescription class)
def galaxy_model(x0, y0, I_PS, PA_bulge, ell_bulge, n, I_e, r_e, PA_disk, ell_disk, I_0, h):
    model = pyimfit.SimpleModelDescription()
    # define the limits on X0 and Y0 as +/-10 pixels relative to initial values
    model.x0.setValue(x0, [x0 - 10, x0 + 10])
    model.y0.setValue(y0, [y0 - 10, y0 + 10])

    nuc = pyimfit.make_imfit_function('Gaussian', label='nucleus')
    nuc.I_0.setValue(I_PS, [0, 10*I_PS])
    nuc.sigma.setValue(0.1, [0, 10])

    bulge = pyimfit.make_imfit_function('Sersic', label='bulge')
    bulge.PA.setValue(PA_bulge, [0, 180])
    bulge.ell.setValue(ell_bulge, [0, 1])
    bulge.I_e.setValue(I_e, [0, 10*I_e])
    bulge.r_e.setValue(r_e, [0, 10*r_e])
    bulge.n.setValue(n, [0.5, 5])

    disk = pyimfit.make_imfit_function('Exponential', label='disk')
    disk.PA.setValue(PA_disk, [0, 180])
    disk.ell.setValue(ell_disk, [0, 1])
    disk.I_0.setValue(I_0, [0, 10*I_0])
    disk.h.setValue(h, [0, 10*h])

    model.addFunction(nuc)
    model.addFunction(bulge)
    model.addFunction(disk)

    return model


x0, y0 = 40., 40.
model_desc = galaxy_model(x0=x0, y0=y0, I_PS=10000000, PA_bulge=90.0, ell_bulge=0.2, n=4, I_e=1,
                        r_e=25*100, PA_disk=90.0, ell_disk=0.5, I_0=1, h=25*100)

imfit_fitter = pyimfit.Imfit(model_desc, psf_model_img)
model_img = imfit_fitter.getModelImage(shape=(100, 100))

plt.imshow(model_img)
plt.savefig('GAL.pdf')
plt.close()

from photutils.aperture import aperture_photometry, CircularAperture

for i in (-2, -1, 0, 1, 2, 3):
	positions = [(x0-i, y0-i)]
	radii = [0.5, 1.0, 1.5, 2.0, 3.0, 5.0, 7.0, 10.0]
	values = []
	last_apphot = 0.0
	for r in radii:
		phot_table = aperture_photometry(model_img, CircularAperture(positions, r=r))
		values.append(float((phot_table['aperture_sum'] - last_apphot) / (2 * 3.14 * r**2)))
		#plt.plot(r, (phot_table['aperture_sum'] - last_apphot) / (2 * 3.14 * r**2), 'x ', color='k')
		last_apphot = phot_table['aperture_sum']
		#plt.plot(r, phot_table['aperture_sum'], 'x ', color='k')
	plt.plot(radii, values, 'x-', label=i)
plt.xlabel('radius [px]')
plt.ylabel('Flux / area')
plt.legend()
plt.savefig('apflux.pdf')
plt.savefig('apflux.png')
plt.close()
```

**Comment by perwin** [comment]
Hi Johannes,

I'll look into this and let you know what I find (thanks for providing the code you're using).

At first glance, I'm a little confused about things being off by _2_ pixels, since I'd expect them to be off by just _one_. This is because PyImfit uses the 1-based image-coordinate scheme that FITS, IRAF, DS9, etc. use (since that's what Imfit uses), while Python of course uses a 0-based scheme. Since you're using the same values (x0 = y0 = 40) for both pyimfit and `aperture_photometry`, there should be an off-by-one problem...

A bit more detail on the pixel-coordinates convention:
https://pyimfit.readthedocs.io/en/latest/pixel_conventions.html

**Comment by perwin** [comment]
Hi Johannes,

OK, I think I've figured out what's going on. There are actually two issues, each of which results in a 1-pixel offset; combined, they produce your apparent two-pixel offset.


I. The first issue is, as I alluded to in my initial response, the offset between how Imfit and PyImfit count pixel coordinates (1-based, as in FITS) and how photutils does it (0-based, as in Python). So when you tell a pyimfit function that the center is at (x0,y0) = (40,40), this corresponds to (39,39) in Python 0-based coordinates. So you ought to be using `x0 - 1` and `y0 - 1` as your input coordinates to `photutils.aperture.aperture_photometry`.


II. The second is that you are using an off-center PSF image for the convolution, which causes a shift in pixel positions for the output image (`model_img`).

Imfit and PyImfit work best if you give them square images with an *odd* number of rows and columns -- e.g., 39 x 39 or 41 x 41 pixels -- with the center of the PSF function in the middle of the central pixel and an equal number of pixel to the left and right (and top and bottom) of that central pixel. (For a 41 x 41-pixel image, the central pixel is at x,y = 20,20 for 1-based coordinates, or 19,19 for 0-based coordinates.)

(This is mentioned in the docs -- https://pyimfit.readthedocs.io/en/latest/psf_convolution.html -- but could probably be a bit more explicit.)

With an even-dimensioned PSF image like you're using (40 x 40 pixels), putting the center of the PSF function at (20,20) as you are doing creates an *asymmetric* image, with 19 pixels to the left of (and below) that pixel and 20 pixels to the right of (and above) that pixel. (I'm thinking in terms of DS9 image display, where the first pixel is in the lower-left corner; you can use the `origin=lower` keyword option in `plt.imshow` to get the same effect.) If you convolve an input image with an off-center PSF like that, the output will be *shifted* by 1 pixel in x and y.

You can see this if you generate the same galaxy image both with and *without* PSF convolution:

```
imfit_fitter_conv = pyimfit.Imfit(model_desc, psf_model_img)
model_img_conv = imfit_fitter_conv.getModelImage(shape=(100, 100))
fits.writeto("gal_conv.fits", model_img_conv)

imfit_fitter_noconv = pyimfit.Imfit(model_desc)
model_img_noconv = imfit_fitter_noconv.getModelImage(shape=(100, 100))
fits.writeto("gal_noconv.fits", model_img_noconv)

```
If you load the two FITS files into DS9 and blink back and forth between them, you can see the offset.


So you ended up with *two* one-pixel offsets (in the same direction), producing the two-pixel offset in the apparent center of the galaxy.


**SOLUTION:** Keep in mind the coordinate offset between how Imfit/PyImfit defines positions and how photutils and numpy/Python defines positions. (Yes, it's awkward, but it seemed better to let PyImfit read unaltered Imfit configuration and best-fit parameter files.) *And also* make sure that your PSF images are properly sized and centered.

(For Imfit/PyImfit 1-based coordinates, the center of your PSF function should be at `x0 = y0 = psf_size // 2`; for Python 0-based coordinates, it would be at `x0 = y0 = psf_size // 2 - 1`, where `psf_size` is the (odd!) width and height of the PSF image.)

**Comment by JohannesBuchner** [comment]
Thank you for the clarification. It works now!
