### ISSUE TITLE
Unable to install due to keyword error

### ISSUE THREAD

**Issue by drhogarth** [perwin/pyimfit#3]
Hi,

I tried to install Pyimfit onto my Ubuntu machine via the pip3 install command, but I'm getting this error when compiling:  **check_gcc_version() got an unexpected keyword argument 'getVersion'**

I checked through your setup.py and believe the error is in **line 212** ( **gccVersionNum = check_gcc_version(getVersion=True)**). In the definition of check_gcc_version, the keyword is **getVersionNum**. I believe this is what is causing the compilation error when installing on Linux when the gcc version is checked.

**Comment by perwin** [comment]
Thanks for letting me know about this! Let me see if I can reproduce and fix this.

**Comment by drhogarth** [comment]
Great. Keep me updated.

**Comment by perwin** [comment]
The newest version (0.10.2) should contain a fix; can you let me know if it works for you?

**Comment by drhogarth** [comment]
Yes it works. Thank you.
